name: amazcart
description: Ezviz Mobile App

publish_to: 'none'

version: 1.2.1+21

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.0.0
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0

  image_picker: ^1.0.4
  dio: ^5.3.2
  persistent_bottom_nav_bar: ^5.0.2
  google_sign_in: ^6.1.5
  expandable: ^5.0.1
  octo_image: ^2.0.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  country_code_picker: ^3.0.0
  # device_preview: ^1.0.0
  pin_code_fields: ^8.0.1
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.7
  dotted_line: ^3.2.2
  expansion_tile_card: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  slide_countdown_clock:
    git: https://github.com/emran92/slide_countdown_clock
  flutter_animation_progress_bar: ^2.3.1
  timelines: ^0.1.0
  clipboard: ^0.1.3
  extended_nested_scroll_view: ^6.1.2
  flutter_swiper_view: ^1.1.8
  another_transformer_page_view: ^2.0.1
  flutter_page_indicator_tv: ^0.0.3-nullsafety
  tabby_flutter_inapp_sdk: ^1.4.0
  flutter_inappwebview: ^5.7.2+3
  #  flutter_page_indicator: ^0.0.3
  #  flutter_page_indicator:
  #    path: ./flutter_page_indicator
  #  transformer_page_view:
  #    path: ./transformer_page_view
  flutter_spinkit: ^5.2.0
  fancy_shimmer_image: ^2.0.3
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  flutter_cupertino_datetime_picker: ^3.0.0
  avatar_glow: ^2.0.2
  file_picker: ^5.5.0
  #  loading_skeleton: ^1.0.2
  loading_skeleton_niu: ^0.0.1
  flutter_easyloading: ^3.0.5
  scratcher: ^2.4.0
  share_plus: ^7.1.0
  radio_grouped_buttons: ^1.0.1
  animate_do: ^3.1.2
  razorpay_flutter: ^1.3.5
  webview_flutter: ^4.2.4
  http_auth: ^1.0.3
  flutter_paystack: ^1.0.7
  #  flutter_paystack:
  #    git:
  #      url: https://github.com/definitelyme/flutter_paystack.git
  #      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  #  flutter_webview_plugin: ^0.4.0
  #  flutter_inappwebview: ^5.3.2
  flutterwave_standard: ^1.0.8
  multi_select_flutter: ^4.1.3
  flutter_xlider: ^3.5.0
  loading_more_list: ^5.0.3
  supercharged: ^2.1.1
  pay: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  #  stripe_sdk: ^5.0.0-nullsafety.0
  #  stripe_payment: ^1.1.3
  flutter_stripe: ^9.4.0

  paytm_allinonesdk: ^1.2.1
  #  easy_search: ^1.0.6+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_html: ^3.0.0-alpha.3
  # sizer: ^2.0.15
  circular_countdown_timer: ^0.2.3
  badges: ^3.1.2
  flutter_facebook_auth: ^6.0.1
  group_radio_button: ^1.3.0
  #  dio_http_cache: ^0.3.0
  flutter_login_facebook: ^1.9.0
  sign_in_with_apple: ^4.3.0
  firebase_auth: ^4.16.0
  crypto: ^3.0.3

  change_app_package_name: ^1.1.0
  flutter_clickpay_bridge: ^2.4.0
  string_to_color: ^2.0.0
  flutter_widget_from_html: ^0.14.11



#dependency_overrides:
#  dio_http_cache: ^0.3.0
dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.7
  flutter_native_splash: ^2.2.8

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/splash_screen_logo.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
#  color: "#FF3364"
  color: "#549cff"
  image: assets/config/splash_screen_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/config/
    - assets/fonts/
    - assets/payment/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf